kind: pipeline
type: docker
name: default

steps:
  - name: Test
    image: node:12
    environment:
      NODE_ENV: development
      SONAR_HOST_URL: https://sonarcloud.io
      SONAR_TOKEN:
        from_secret: SECRET_SONAR_TOKEN
    commands:
      - npm install
      - npm run coverage
      - npm run sonar
