kind: pipeline
type: docker
name: default

steps:
  - name: Test
    image: node:12
    environment:
      NODE_ENV: development
    commands:
      - npm install
      - npm run coverage
      - export
      - npm run sonar
